services:
  gateway:
    profiles:
      - docker-gateway

  frontend:
    build:
      context: ./frontend
    ports:
      - "127.0.0.1:3100:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "127.0.0.1:3101:3001"
